# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  rg: 'practise1'
  stg: 'storage_account'
  container: 'tfstate'
  pipeline: 'pipeline.terraform.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmResourceGroupName: '$(rg)'
              backendAzureRmStorageAccountName: '$(stg)'
              backendAzureRmContainerName: '$(container)'
              backendAzureRmKey: '$(pipeline)'
              backendServiceArm: '681bc5ef-e95b-448e-a75c-95b847392d6e'
          - task: TerraformTask@5
            displayName: tfvalidate
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTask@5
            displayName: tfplan
            inputs:
              provider: 'azurerm'
              command: 'plan'
  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmResourceGroupName: '$(rg)'
              backendAzureRmStorageAccountName: '$(stg)'
              backendAzureRmContainerName: '$(container)'
              backendAzureRmKey: '$(pipeline)'
              backendServiceArm: '681bc5ef-e95b-448e-a75c-95b847392d6e'

          - task: TerraformTask@5
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
          - task: TerraformTask@5
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
           
          
